name: .NET Core Test

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened, edited ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [win-x64, linux-x64, osx-x64]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        # SDK version to use. Example: 2.2.104
        dotnet-version: 2.1.801
      
    - name: dotnet publish test
      run: cd Chip8CSharp;dotnet publish -c Release -r ${{ matrix.os }}
  wip:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: wip/action@v1.0.0
    
