name: .NET Core Bump Version

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        # SDK version to use. Example: 2.2.104
        dotnet-version: 2.1.801
      
    - name: Install Dotnet version tool
      run: dotnet tool install -g dotnet-version-cli
    
    - name: Set environmental variable for version
      run: echo ::set-env name=PROJECT_VERSION::$(dotnet version --project-file /home/runner/work/Chip8CSharp/Chip8CSharp/Chip8CSharp/Chip8CSharp.csproj | grep -v v | tr -d "[:space:]")
    
    - name: find current PR
      uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Apply Patch
      if: contains(steps.findPr.outputs.title, 'patch')
      run: dotnet version -f /home/runner/work/Chip8CSharp/Chip8CSharp/Chip8CSharp/Chip8CSharp.csproj patch
      continue-on-error: true
      
    - name: Apply Minor
      if: contains(steps.findPr.outputs.title, 'minor')
      run: dotnet version -f /home/runner/work/Chip8CSharp/Chip8CSharp/Chip8CSharp/Chip8CSharp.csproj minor
      continue-on-error: true
      
    - name: Apply Major
      if: contains(steps.findPr.outputs.title, 'major')
      run: dotnet version -f /home/runner/work/Chip8CSharp/Chip8CSharp/Chip8CSharp/Chip8CSharp.csproj major
      continue-on-error: true
    
    - name: Set environmental variable for new version
      run: echo ::set-env name=PROJECT_VERSION::$(dotnet version --project-file /home/runner/work/Chip8CSharp/Chip8CSharp/Chip8CSharp/Chip8CSharp.csproj | grep -v v | tr -d "[:space:]")
    
    - name: git global configuration
      run: |
        git config --global user.name "Dotnet autobuilder"
        git config --global user.email autobuilder@dotnet.com
    
    - name: commit
      continue-on-error: true
      run: |
        git add /home/runner/work/Chip8CSharp/Chip8CSharp/Chip8CSharp/Chip8CSharp.csproj
        git commit -m "Release v${{ env.PROJECT_VERSION }}"
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      continue-on-error: true
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true 
    
    - name: Validate job
      run: echo 'valid'
